# Generated by Django 2.0 on 2022-02-09 08:44

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220209_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
